# Generated by Django 3.1.1 on 2020-09-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200915_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='mergeCommit',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
