# Generated by Django 3.1.1 on 2020-09-15 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200915_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commit',
            old_name='authordate',
            new_name='authorDate',
        ),
        migrations.RenameField(
            model_name='commit',
            old_name='commitdate',
            new_name='commitDate',
        ),
    ]
