# Generated by Django 3.1.1 on 2020-09-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200915_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='authorDate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commit',
            name='commitDate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
