# Generated by Django 3.1.1 on 2020-09-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200915_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics',
            name='management',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='tests',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
