# Generated by Django 3.1.1 on 2020-09-15 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200915_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='metrics',
        ),
    ]
