# Generated by Django 3.1.1 on 2020-09-15 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_repository_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrics',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.repository'),
        ),
    ]
