# Generated by Django 3.1.1 on 2020-09-16 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200915_1831'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MapIdentification',
            new_name='LocalMapIdentification',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='pullrequest',
            name='comments',
        ),
        migrations.CreateModel(
            name='GlobalMapIdentification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField()),
                ('algorithm', models.TextField()),
                ('identification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.identification')),
            ],
        ),
    ]
