# Generated by Django 3.1.1 on 2020-10-15 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_validator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Validator',
        ),
    ]
